print("Savannah Davis")
print("August 23, 2023")
print("I am signing up for Replit's 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE. Looking forward to building something!")
print("I'm feeling 😊.")
print("You can follow my progress at @ https://github.com/SavannahNDavis")
